import {
  ArrowDownToLine,
  ArrowUpFromLine,
  CreditCard,
  RotateCcw,
  Wallet,
  DollarSign,
  BarChart3,
  Activity,
} from "lucide-react";
import type { OverviewCardData } from "@/interfaces/overviewCard.interface";

export const overviewCards: OverviewCardData[] = [
  {
    id: "deposits",
    title: "Deposits",
    value: "$24,500.00",
    metadata: "+12% from last month",
    icon: ArrowDownToLine,
    iconColor: "text-emerald-600",
    iconBg: "bg-emerald-50",
  },
  {
    id: "withdrawals",
    title: "Withdrawals",
    value: "$8,200.00",
    metadata: "-3% from last month",
    icon: ArrowUpFromLine,
    iconColor: "text-red-600",
    iconBg: "bg-red-50",
  },
  {
    id: "topups",
    title: "Top Ups",
    value: "$12,800.00",
    metadata: "+8% from last month",
    icon: CreditCard,
    iconColor: "text-blue-600",
    iconBg: "bg-blue-50",
  },
  {
    id: "refunds",
    title: "Refunds",
    value: "$1,400.00",
    metadata: "2 pending refunds",
    icon: RotateCcw,
    iconColor: "text-amber-600",
    iconBg: "bg-amber-50",
  },
  {
    id: "wallet-balance",
    title: "Wallet Balance",
    value: "$15,300.00",
    metadata: "Available balance",
    icon: Wallet,
    iconColor: "text-violet-600",
    iconBg: "bg-violet-50",
  },
  {
    id: "usd-rate",
    title: "Current USD Rate",
    value: "৳119.50",
    metadata: "Updated today",
    icon: DollarSign,
    iconColor: "text-teal-600",
    iconBg: "bg-teal-50",
  },
  {
    id: "ad-balance",
    title: "Ad Account Balance",
    value: "$6,320.00",
    metadata: "Across all accounts",
    icon: BarChart3,
    iconColor: "text-indigo-600",
    iconBg: "bg-indigo-50",
  },
  {
    id: "active-ad-accounts",
    title: "Active Ad Accounts",
    value: "12",
    metadata: "3 pending approval",
    icon: Activity,
    iconColor: "text-pink-600",
    iconBg: "bg-pink-50",
  },
];
